# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBQHmyG7NriGKwHqbwqNuNqzM6poSG6o
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv('imdb_top_1000.csv')


df.columns = df.columns.str.strip()


df = df.dropna(subset=['IMDB_Rating'])
ratings = df['IMDB_Rating']


mean_rating = ratings.mean()
median_rating = ratings.median()
mode_rating = ratings.mode()[0]
std_rating = ratings.std()

print("Mean IMDB Rating:", mean_rating)
print("Median IMDB Rating:", median_rating)
print("Mode IMDB Rating:", mode_rating)
print("Standard Deviation:", std_rating)

min_val = ratings.min()
max_val = ratings.max()

bins = np.arange(min_val, max_val + 0.5, 0.5)


labels = [f"{round(bins[i],1)}-{round(bins[i+1],1)}" for i in range(len(bins)-1)]


df['Rating_Class'] = pd.cut(df['IMDB_Rating'], bins=bins, labels=labels, include_lowest=True)


freq_table = df['Rating_Class'].value_counts().sort_index()

print("\nFrequency Distribution:")
print(freq_table)

modal_class = freq_table.idxmax()
modal_class_freq = freq_table.max()

print("\nModal Class:", modal_class)
print("Frequency of Modal Class:", modal_class_freq)


plt.figure(figsize=(8,5))
plt.hist(ratings, bins=bins, edgecolor='black')

plt.xlabel('IMDB Rating')
plt.ylabel('Frequency')
plt.title('Histogram of IMDB Ratings (Class Width = 0.5)')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()